/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/_app/subscription'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/_app/requests'
import { Route as AuthenticatedAppPremiumRouteImport } from './routes/_authenticated/_app/premium'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app/notifications'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/_app/home'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/_app/discover'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/_app/create'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app/chat'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/_app/settings.index'
import { Route as AuthenticatedAppProfileIndexRouteImport } from './routes/_authenticated/_app/profile.index'
import { Route as AuthenticatedAppPrideIndexRouteImport } from './routes/_authenticated/_app/pride.index'
import { Route as AuthenticatedAppMessagesIndexRouteImport } from './routes/_authenticated/_app/messages.index'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated/_app/events.index'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated/_app/u.$userId'
import { Route as AuthenticatedAppSettingsReportRouteImport } from './routes/_authenticated/_app/settings.report'
import { Route as AuthenticatedAppSettingsPhoneRouteImport } from './routes/_authenticated/_app/settings.phone'
import { Route as AuthenticatedAppSettingsPasswordRouteImport } from './routes/_authenticated/_app/settings.password'
import { Route as AuthenticatedAppSettingsBlockedRouteImport } from './routes/_authenticated/_app/settings.blocked'
import { Route as AuthenticatedAppProfileEditRouteImport } from './routes/_authenticated/_app/profile.edit'
import { Route as AuthenticatedAppPrideSetupRouteImport } from './routes/_authenticated/_app/pride.setup'
import { Route as AuthenticatedAppPrideNotificationsRouteImport } from './routes/_authenticated/_app/pride.notifications'
import { Route as AuthenticatedAppPostsPostIdRouteImport } from './routes/_authenticated/_app/posts.$postId'
import { Route as AuthenticatedAppMessagesThreadIdRouteImport } from './routes/_authenticated/_app/messages.$threadId'
import { Route as AuthenticatedAppChatGroupIdRouteImport } from './routes/_authenticated/_app/chat.$groupId'
import { Route as AuthenticatedAppEventsEventIdIndexRouteImport } from './routes/_authenticated/_app/events.$eventId.index'
import { Route as AuthenticatedAppEventsEventIdEditRouteImport } from './routes/_authenticated/_app/events.$eventId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPremiumRoute = AuthenticatedAppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileIndexRoute =
  AuthenticatedAppProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideIndexRoute =
  AuthenticatedAppPrideIndexRouteImport.update({
    id: '/pride/',
    path: '/pride/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesIndexRoute =
  AuthenticatedAppMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsReportRoute =
  AuthenticatedAppSettingsReportRouteImport.update({
    id: '/settings/report',
    path: '/settings/report',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsPhoneRoute =
  AuthenticatedAppSettingsPhoneRouteImport.update({
    id: '/settings/phone',
    path: '/settings/phone',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsPasswordRoute =
  AuthenticatedAppSettingsPasswordRouteImport.update({
    id: '/settings/password',
    path: '/settings/password',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsBlockedRoute =
  AuthenticatedAppSettingsBlockedRouteImport.update({
    id: '/settings/blocked',
    path: '/settings/blocked',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileEditRoute =
  AuthenticatedAppProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideSetupRoute =
  AuthenticatedAppPrideSetupRouteImport.update({
    id: '/pride/setup',
    path: '/pride/setup',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideNotificationsRoute =
  AuthenticatedAppPrideNotificationsRouteImport.update({
    id: '/pride/notifications',
    path: '/pride/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPostsPostIdRoute =
  AuthenticatedAppPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesThreadIdRoute =
  AuthenticatedAppMessagesThreadIdRouteImport.update({
    id: '/messages/$threadId',
    path: '/messages/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatGroupIdRoute =
  AuthenticatedAppChatGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppEventsEventIdIndexRoute =
  AuthenticatedAppEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsEventIdEditRoute =
  AuthenticatedAppEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/create': typeof AuthenticatedAppCreateRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/events/': typeof AuthenticatedAppEventsIndexRoute
  '/messages/': typeof AuthenticatedAppMessagesIndexRoute
  '/pride/': typeof AuthenticatedAppPrideIndexRoute
  '/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/create': typeof AuthenticatedAppCreateRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/events': typeof AuthenticatedAppEventsIndexRoute
  '/messages': typeof AuthenticatedAppMessagesIndexRoute
  '/pride': typeof AuthenticatedAppPrideIndexRoute
  '/profile': typeof AuthenticatedAppProfileIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/events/$eventId': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/_app/create': typeof AuthenticatedAppCreateRoute
  '/_authenticated/_app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/_app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/premium': typeof AuthenticatedAppPremiumRoute
  '/_authenticated/_app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/_app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/_app/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/_authenticated/_app/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/_authenticated/_app/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/_authenticated/_app/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/_authenticated/_app/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/_authenticated/_app/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/_authenticated/_app/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/_authenticated/_app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/_authenticated/_app/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/_authenticated/_app/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/_authenticated/_app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/_authenticated/_app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/_app/messages/': typeof AuthenticatedAppMessagesIndexRoute
  '/_authenticated/_app/pride/': typeof AuthenticatedAppPrideIndexRoute
  '/_authenticated/_app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/_authenticated/_app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/onboarding'
    | '/pending'
    | '/admin/events'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/chat'
    | '/create'
    | '/discover'
    | '/home'
    | '/notifications'
    | '/premium'
    | '/requests'
    | '/subscription'
    | '/api/public/razorpay-webhook'
    | '/chat/$groupId'
    | '/messages/$threadId'
    | '/posts/$postId'
    | '/pride/notifications'
    | '/pride/setup'
    | '/profile/edit'
    | '/settings/blocked'
    | '/settings/password'
    | '/settings/phone'
    | '/settings/report'
    | '/u/$userId'
    | '/events/'
    | '/messages/'
    | '/pride/'
    | '/profile/'
    | '/settings/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/onboarding'
    | '/pending'
    | '/admin/events'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/chat'
    | '/create'
    | '/discover'
    | '/home'
    | '/notifications'
    | '/premium'
    | '/requests'
    | '/subscription'
    | '/api/public/razorpay-webhook'
    | '/chat/$groupId'
    | '/messages/$threadId'
    | '/posts/$postId'
    | '/pride/notifications'
    | '/pride/setup'
    | '/profile/edit'
    | '/settings/blocked'
    | '/settings/password'
    | '/settings/phone'
    | '/settings/report'
    | '/u/$userId'
    | '/events'
    | '/messages'
    | '/pride'
    | '/profile'
    | '/settings'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending'
    | '/admin/events'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/create'
    | '/_authenticated/_app/discover'
    | '/_authenticated/_app/home'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/premium'
    | '/_authenticated/_app/requests'
    | '/_authenticated/_app/subscription'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/_app/chat/$groupId'
    | '/_authenticated/_app/messages/$threadId'
    | '/_authenticated/_app/posts/$postId'
    | '/_authenticated/_app/pride/notifications'
    | '/_authenticated/_app/pride/setup'
    | '/_authenticated/_app/profile/edit'
    | '/_authenticated/_app/settings/blocked'
    | '/_authenticated/_app/settings/password'
    | '/_authenticated/_app/settings/phone'
    | '/_authenticated/_app/settings/report'
    | '/_authenticated/_app/u/$userId'
    | '/_authenticated/_app/events/'
    | '/_authenticated/_app/messages/'
    | '/_authenticated/_app/pride/'
    | '/_authenticated/_app/profile/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/events/$eventId/edit'
    | '/_authenticated/_app/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/subscription': {
      id: '/_authenticated/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/requests': {
      id: '/_authenticated/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/premium': {
      id: '/_authenticated/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedAppPremiumRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/home': {
      id: '/_authenticated/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/discover': {
      id: '/_authenticated/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/create': {
      id: '/_authenticated/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/': {
      id: '/_authenticated/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedAppProfileIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/': {
      id: '/_authenticated/_app/pride/'
      path: '/pride'
      fullPath: '/pride/'
      preLoaderRoute: typeof AuthenticatedAppPrideIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/': {
      id: '/_authenticated/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedAppMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events/': {
      id: '/_authenticated/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/u/$userId': {
      id: '/_authenticated/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/report': {
      id: '/_authenticated/_app/settings/report'
      path: '/settings/report'
      fullPath: '/settings/report'
      preLoaderRoute: typeof AuthenticatedAppSettingsReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/phone': {
      id: '/_authenticated/_app/settings/phone'
      path: '/settings/phone'
      fullPath: '/settings/phone'
      preLoaderRoute: typeof AuthenticatedAppSettingsPhoneRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/password': {
      id: '/_authenticated/_app/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedAppSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/blocked': {
      id: '/_authenticated/_app/settings/blocked'
      path: '/settings/blocked'
      fullPath: '/settings/blocked'
      preLoaderRoute: typeof AuthenticatedAppSettingsBlockedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/edit': {
      id: '/_authenticated/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedAppProfileEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/setup': {
      id: '/_authenticated/_app/pride/setup'
      path: '/pride/setup'
      fullPath: '/pride/setup'
      preLoaderRoute: typeof AuthenticatedAppPrideSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/notifications': {
      id: '/_authenticated/_app/pride/notifications'
      path: '/pride/notifications'
      fullPath: '/pride/notifications'
      preLoaderRoute: typeof AuthenticatedAppPrideNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/posts/$postId': {
      id: '/_authenticated/_app/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedAppPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/$threadId': {
      id: '/_authenticated/_app/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedAppMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat/$groupId': {
      id: '/_authenticated/_app/chat/$groupId'
      path: '/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedAppChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/_app/events/$eventId/': {
      id: '/_authenticated/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events/$eventId/edit': {
      id: '/_authenticated/_app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatGroupIdRoute: typeof AuthenticatedAppChatGroupIdRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatGroupIdRoute: AuthenticatedAppChatGroupIdRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRoute
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPremiumRoute: typeof AuthenticatedAppPremiumRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppMessagesThreadIdRoute: typeof AuthenticatedAppMessagesThreadIdRoute
  AuthenticatedAppPostsPostIdRoute: typeof AuthenticatedAppPostsPostIdRoute
  AuthenticatedAppPrideNotificationsRoute: typeof AuthenticatedAppPrideNotificationsRoute
  AuthenticatedAppPrideSetupRoute: typeof AuthenticatedAppPrideSetupRoute
  AuthenticatedAppProfileEditRoute: typeof AuthenticatedAppProfileEditRoute
  AuthenticatedAppSettingsBlockedRoute: typeof AuthenticatedAppSettingsBlockedRoute
  AuthenticatedAppSettingsPasswordRoute: typeof AuthenticatedAppSettingsPasswordRoute
  AuthenticatedAppSettingsPhoneRoute: typeof AuthenticatedAppSettingsPhoneRoute
  AuthenticatedAppSettingsReportRoute: typeof AuthenticatedAppSettingsReportRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppMessagesIndexRoute: typeof AuthenticatedAppMessagesIndexRoute
  AuthenticatedAppPrideIndexRoute: typeof AuthenticatedAppPrideIndexRoute
  AuthenticatedAppProfileIndexRoute: typeof AuthenticatedAppProfileIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppEventsEventIdEditRoute: typeof AuthenticatedAppEventsEventIdEditRoute
  AuthenticatedAppEventsEventIdIndexRoute: typeof AuthenticatedAppEventsEventIdIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRoute,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPremiumRoute: AuthenticatedAppPremiumRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppMessagesThreadIdRoute: AuthenticatedAppMessagesThreadIdRoute,
  AuthenticatedAppPostsPostIdRoute: AuthenticatedAppPostsPostIdRoute,
  AuthenticatedAppPrideNotificationsRoute:
    AuthenticatedAppPrideNotificationsRoute,
  AuthenticatedAppPrideSetupRoute: AuthenticatedAppPrideSetupRoute,
  AuthenticatedAppProfileEditRoute: AuthenticatedAppProfileEditRoute,
  AuthenticatedAppSettingsBlockedRoute: AuthenticatedAppSettingsBlockedRoute,
  AuthenticatedAppSettingsPasswordRoute: AuthenticatedAppSettingsPasswordRoute,
  AuthenticatedAppSettingsPhoneRoute: AuthenticatedAppSettingsPhoneRoute,
  AuthenticatedAppSettingsReportRoute: AuthenticatedAppSettingsReportRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
  AuthenticatedAppMessagesIndexRoute: AuthenticatedAppMessagesIndexRoute,
  AuthenticatedAppPrideIndexRoute: AuthenticatedAppPrideIndexRoute,
  AuthenticatedAppProfileIndexRoute: AuthenticatedAppProfileIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppEventsEventIdEditRoute:
    AuthenticatedAppEventsEventIdEditRoute,
  AuthenticatedAppEventsEventIdIndexRoute:
    AuthenticatedAppEventsEventIdIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
