/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminFlaggedRouteImport } from './routes/admin.flagged'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEngagementRouteImport } from './routes/admin.engagement'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/_app/subscription'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/_app/requests'
import { Route as AuthenticatedAppPremiumRouteImport } from './routes/_authenticated/_app/premium'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app/notifications'
import { Route as AuthenticatedAppIcebreakerRouteImport } from './routes/_authenticated/_app/icebreaker'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/_app/home'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/_app/discover'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/_app/create'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/_app/settings.index'
import { Route as AuthenticatedAppRewardsIndexRouteImport } from './routes/_authenticated/_app/rewards.index'
import { Route as AuthenticatedAppProfileIndexRouteImport } from './routes/_authenticated/_app/profile.index'
import { Route as AuthenticatedAppPrideIndexRouteImport } from './routes/_authenticated/_app/pride.index'
import { Route as AuthenticatedAppMessagesIndexRouteImport } from './routes/_authenticated/_app/messages.index'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated/_app/events.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/_app/chat.index'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated/_app/u.$userId'
import { Route as AuthenticatedAppSettingsTermsRouteImport } from './routes/_authenticated/_app/settings.terms'
import { Route as AuthenticatedAppSettingsReportRouteImport } from './routes/_authenticated/_app/settings.report'
import { Route as AuthenticatedAppSettingsPrivacyRouteImport } from './routes/_authenticated/_app/settings.privacy'
import { Route as AuthenticatedAppSettingsPhoneRouteImport } from './routes/_authenticated/_app/settings.phone'
import { Route as AuthenticatedAppSettingsPasswordRouteImport } from './routes/_authenticated/_app/settings.password'
import { Route as AuthenticatedAppSettingsHelpRouteImport } from './routes/_authenticated/_app/settings.help'
import { Route as AuthenticatedAppSettingsBlockedRouteImport } from './routes/_authenticated/_app/settings.blocked'
import { Route as AuthenticatedAppProfileEditRouteImport } from './routes/_authenticated/_app/profile.edit'
import { Route as AuthenticatedAppPrideSetupRouteImport } from './routes/_authenticated/_app/pride.setup'
import { Route as AuthenticatedAppPrideNotificationsRouteImport } from './routes/_authenticated/_app/pride.notifications'
import { Route as AuthenticatedAppPrideGuidelinesRouteImport } from './routes/_authenticated/_app/pride.guidelines'
import { Route as AuthenticatedAppPostsPostIdRouteImport } from './routes/_authenticated/_app/posts.$postId'
import { Route as AuthenticatedAppMessagesThreadIdRouteImport } from './routes/_authenticated/_app/messages.$threadId'
import { Route as AuthenticatedAppChatGroupIdRouteImport } from './routes/_authenticated/_app/chat.$groupId'
import { Route as AuthenticatedAppEventsEventIdIndexRouteImport } from './routes/_authenticated/_app/events.$eventId.index'
import { Route as AuthenticatedAppEventsEventIdEditRouteImport } from './routes/_authenticated/_app/events.$eventId.edit'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlaggedRoute = AdminFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngagementRoute = AdminEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPremiumRoute = AuthenticatedAppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIcebreakerRoute =
  AuthenticatedAppIcebreakerRouteImport.update({
    id: '/icebreaker',
    path: '/icebreaker',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRewardsIndexRoute =
  AuthenticatedAppRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileIndexRoute =
  AuthenticatedAppProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideIndexRoute =
  AuthenticatedAppPrideIndexRouteImport.update({
    id: '/pride/',
    path: '/pride/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesIndexRoute =
  AuthenticatedAppMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsTermsRoute =
  AuthenticatedAppSettingsTermsRouteImport.update({
    id: '/settings/terms',
    path: '/settings/terms',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsReportRoute =
  AuthenticatedAppSettingsReportRouteImport.update({
    id: '/settings/report',
    path: '/settings/report',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsPrivacyRoute =
  AuthenticatedAppSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsPhoneRoute =
  AuthenticatedAppSettingsPhoneRouteImport.update({
    id: '/settings/phone',
    path: '/settings/phone',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsPasswordRoute =
  AuthenticatedAppSettingsPasswordRouteImport.update({
    id: '/settings/password',
    path: '/settings/password',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsHelpRoute =
  AuthenticatedAppSettingsHelpRouteImport.update({
    id: '/settings/help',
    path: '/settings/help',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsBlockedRoute =
  AuthenticatedAppSettingsBlockedRouteImport.update({
    id: '/settings/blocked',
    path: '/settings/blocked',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileEditRoute =
  AuthenticatedAppProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideSetupRoute =
  AuthenticatedAppPrideSetupRouteImport.update({
    id: '/pride/setup',
    path: '/pride/setup',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideNotificationsRoute =
  AuthenticatedAppPrideNotificationsRouteImport.update({
    id: '/pride/notifications',
    path: '/pride/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrideGuidelinesRoute =
  AuthenticatedAppPrideGuidelinesRouteImport.update({
    id: '/pride/guidelines',
    path: '/pride/guidelines',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPostsPostIdRoute =
  AuthenticatedAppPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesThreadIdRoute =
  AuthenticatedAppMessagesThreadIdRouteImport.update({
    id: '/messages/$threadId',
    path: '/messages/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatGroupIdRoute =
  AuthenticatedAppChatGroupIdRouteImport.update({
    id: '/chat/$groupId',
    path: '/chat/$groupId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsEventIdIndexRoute =
  AuthenticatedAppEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsEventIdEditRoute =
  AuthenticatedAppEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/': typeof AdminIndexRoute
  '/create': typeof AuthenticatedAppCreateRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/icebreaker': typeof AuthenticatedAppIcebreakerRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/pride/guidelines': typeof AuthenticatedAppPrideGuidelinesRoute
  '/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/settings/help': typeof AuthenticatedAppSettingsHelpRoute
  '/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/settings/terms': typeof AuthenticatedAppSettingsTermsRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/chat/': typeof AuthenticatedAppChatIndexRoute
  '/events/': typeof AuthenticatedAppEventsIndexRoute
  '/messages/': typeof AuthenticatedAppMessagesIndexRoute
  '/pride/': typeof AuthenticatedAppPrideIndexRoute
  '/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/rewards/': typeof AuthenticatedAppRewardsIndexRoute
  '/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin': typeof AdminIndexRoute
  '/create': typeof AuthenticatedAppCreateRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/icebreaker': typeof AuthenticatedAppIcebreakerRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/pride/guidelines': typeof AuthenticatedAppPrideGuidelinesRoute
  '/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/settings/help': typeof AuthenticatedAppSettingsHelpRoute
  '/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/settings/terms': typeof AuthenticatedAppSettingsTermsRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/chat': typeof AuthenticatedAppChatIndexRoute
  '/events': typeof AuthenticatedAppEventsIndexRoute
  '/messages': typeof AuthenticatedAppMessagesIndexRoute
  '/pride': typeof AuthenticatedAppPrideIndexRoute
  '/profile': typeof AuthenticatedAppProfileIndexRoute
  '/rewards': typeof AuthenticatedAppRewardsIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/events/$eventId': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/_app/create': typeof AuthenticatedAppCreateRoute
  '/_authenticated/_app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/_app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/_app/icebreaker': typeof AuthenticatedAppIcebreakerRoute
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/premium': typeof AuthenticatedAppPremiumRoute
  '/_authenticated/_app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/_app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/_authenticated/_app/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/_authenticated/_app/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/_authenticated/_app/posts/$postId': typeof AuthenticatedAppPostsPostIdRoute
  '/_authenticated/_app/pride/guidelines': typeof AuthenticatedAppPrideGuidelinesRoute
  '/_authenticated/_app/pride/notifications': typeof AuthenticatedAppPrideNotificationsRoute
  '/_authenticated/_app/pride/setup': typeof AuthenticatedAppPrideSetupRoute
  '/_authenticated/_app/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/_authenticated/_app/settings/blocked': typeof AuthenticatedAppSettingsBlockedRoute
  '/_authenticated/_app/settings/help': typeof AuthenticatedAppSettingsHelpRoute
  '/_authenticated/_app/settings/password': typeof AuthenticatedAppSettingsPasswordRoute
  '/_authenticated/_app/settings/phone': typeof AuthenticatedAppSettingsPhoneRoute
  '/_authenticated/_app/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/_authenticated/_app/settings/report': typeof AuthenticatedAppSettingsReportRoute
  '/_authenticated/_app/settings/terms': typeof AuthenticatedAppSettingsTermsRoute
  '/_authenticated/_app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/_authenticated/_app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/_app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/_app/messages/': typeof AuthenticatedAppMessagesIndexRoute
  '/_authenticated/_app/pride/': typeof AuthenticatedAppPrideIndexRoute
  '/_authenticated/_app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/_authenticated/_app/rewards/': typeof AuthenticatedAppRewardsIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/_authenticated/_app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/pending'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/flagged'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/'
    | '/create'
    | '/discover'
    | '/home'
    | '/icebreaker'
    | '/notifications'
    | '/premium'
    | '/requests'
    | '/subscription'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-push'
    | '/chat/$groupId'
    | '/messages/$threadId'
    | '/posts/$postId'
    | '/pride/guidelines'
    | '/pride/notifications'
    | '/pride/setup'
    | '/profile/edit'
    | '/settings/blocked'
    | '/settings/help'
    | '/settings/password'
    | '/settings/phone'
    | '/settings/privacy'
    | '/settings/report'
    | '/settings/terms'
    | '/u/$userId'
    | '/chat/'
    | '/events/'
    | '/messages/'
    | '/pride/'
    | '/profile/'
    | '/rewards/'
    | '/settings/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/pending'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/flagged'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin'
    | '/create'
    | '/discover'
    | '/home'
    | '/icebreaker'
    | '/notifications'
    | '/premium'
    | '/requests'
    | '/subscription'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-push'
    | '/chat/$groupId'
    | '/messages/$threadId'
    | '/posts/$postId'
    | '/pride/guidelines'
    | '/pride/notifications'
    | '/pride/setup'
    | '/profile/edit'
    | '/settings/blocked'
    | '/settings/help'
    | '/settings/password'
    | '/settings/phone'
    | '/settings/privacy'
    | '/settings/report'
    | '/settings/terms'
    | '/u/$userId'
    | '/chat'
    | '/events'
    | '/messages'
    | '/pride'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/forgot-password'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/flagged'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/'
    | '/_authenticated/_app/create'
    | '/_authenticated/_app/discover'
    | '/_authenticated/_app/home'
    | '/_authenticated/_app/icebreaker'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/premium'
    | '/_authenticated/_app/requests'
    | '/_authenticated/_app/subscription'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-push'
    | '/_authenticated/_app/chat/$groupId'
    | '/_authenticated/_app/messages/$threadId'
    | '/_authenticated/_app/posts/$postId'
    | '/_authenticated/_app/pride/guidelines'
    | '/_authenticated/_app/pride/notifications'
    | '/_authenticated/_app/pride/setup'
    | '/_authenticated/_app/profile/edit'
    | '/_authenticated/_app/settings/blocked'
    | '/_authenticated/_app/settings/help'
    | '/_authenticated/_app/settings/password'
    | '/_authenticated/_app/settings/phone'
    | '/_authenticated/_app/settings/privacy'
    | '/_authenticated/_app/settings/report'
    | '/_authenticated/_app/settings/terms'
    | '/_authenticated/_app/u/$userId'
    | '/_authenticated/_app/chat/'
    | '/_authenticated/_app/events/'
    | '/_authenticated/_app/messages/'
    | '/_authenticated/_app/pride/'
    | '/_authenticated/_app/profile/'
    | '/_authenticated/_app/rewards/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/events/$eventId/edit'
    | '/_authenticated/_app/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flagged': {
      id: '/admin/flagged'
      path: '/flagged'
      fullPath: '/admin/flagged'
      preLoaderRoute: typeof AdminFlaggedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engagement': {
      id: '/admin/engagement'
      path: '/engagement'
      fullPath: '/admin/engagement'
      preLoaderRoute: typeof AdminEngagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/subscription': {
      id: '/_authenticated/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/requests': {
      id: '/_authenticated/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/premium': {
      id: '/_authenticated/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedAppPremiumRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/icebreaker': {
      id: '/_authenticated/_app/icebreaker'
      path: '/icebreaker'
      fullPath: '/icebreaker'
      preLoaderRoute: typeof AuthenticatedAppIcebreakerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/home': {
      id: '/_authenticated/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/discover': {
      id: '/_authenticated/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/create': {
      id: '/_authenticated/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/rewards/': {
      id: '/_authenticated/_app/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof AuthenticatedAppRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/': {
      id: '/_authenticated/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedAppProfileIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/': {
      id: '/_authenticated/_app/pride/'
      path: '/pride'
      fullPath: '/pride/'
      preLoaderRoute: typeof AuthenticatedAppPrideIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/': {
      id: '/_authenticated/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedAppMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events/': {
      id: '/_authenticated/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat/': {
      id: '/_authenticated/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/u/$userId': {
      id: '/_authenticated/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/terms': {
      id: '/_authenticated/_app/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof AuthenticatedAppSettingsTermsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/report': {
      id: '/_authenticated/_app/settings/report'
      path: '/settings/report'
      fullPath: '/settings/report'
      preLoaderRoute: typeof AuthenticatedAppSettingsReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/privacy': {
      id: '/_authenticated/_app/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedAppSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/phone': {
      id: '/_authenticated/_app/settings/phone'
      path: '/settings/phone'
      fullPath: '/settings/phone'
      preLoaderRoute: typeof AuthenticatedAppSettingsPhoneRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/password': {
      id: '/_authenticated/_app/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedAppSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/help': {
      id: '/_authenticated/_app/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AuthenticatedAppSettingsHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/blocked': {
      id: '/_authenticated/_app/settings/blocked'
      path: '/settings/blocked'
      fullPath: '/settings/blocked'
      preLoaderRoute: typeof AuthenticatedAppSettingsBlockedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/edit': {
      id: '/_authenticated/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedAppProfileEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/setup': {
      id: '/_authenticated/_app/pride/setup'
      path: '/pride/setup'
      fullPath: '/pride/setup'
      preLoaderRoute: typeof AuthenticatedAppPrideSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/notifications': {
      id: '/_authenticated/_app/pride/notifications'
      path: '/pride/notifications'
      fullPath: '/pride/notifications'
      preLoaderRoute: typeof AuthenticatedAppPrideNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pride/guidelines': {
      id: '/_authenticated/_app/pride/guidelines'
      path: '/pride/guidelines'
      fullPath: '/pride/guidelines'
      preLoaderRoute: typeof AuthenticatedAppPrideGuidelinesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/posts/$postId': {
      id: '/_authenticated/_app/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedAppPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/$threadId': {
      id: '/_authenticated/_app/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedAppMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat/$groupId': {
      id: '/_authenticated/_app/chat/$groupId'
      path: '/chat/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedAppChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events/$eventId/': {
      id: '/_authenticated/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events/$eventId/edit': {
      id: '/_authenticated/_app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRoute
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppIcebreakerRoute: typeof AuthenticatedAppIcebreakerRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPremiumRoute: typeof AuthenticatedAppPremiumRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppChatGroupIdRoute: typeof AuthenticatedAppChatGroupIdRoute
  AuthenticatedAppMessagesThreadIdRoute: typeof AuthenticatedAppMessagesThreadIdRoute
  AuthenticatedAppPostsPostIdRoute: typeof AuthenticatedAppPostsPostIdRoute
  AuthenticatedAppPrideGuidelinesRoute: typeof AuthenticatedAppPrideGuidelinesRoute
  AuthenticatedAppPrideNotificationsRoute: typeof AuthenticatedAppPrideNotificationsRoute
  AuthenticatedAppPrideSetupRoute: typeof AuthenticatedAppPrideSetupRoute
  AuthenticatedAppProfileEditRoute: typeof AuthenticatedAppProfileEditRoute
  AuthenticatedAppSettingsBlockedRoute: typeof AuthenticatedAppSettingsBlockedRoute
  AuthenticatedAppSettingsHelpRoute: typeof AuthenticatedAppSettingsHelpRoute
  AuthenticatedAppSettingsPasswordRoute: typeof AuthenticatedAppSettingsPasswordRoute
  AuthenticatedAppSettingsPhoneRoute: typeof AuthenticatedAppSettingsPhoneRoute
  AuthenticatedAppSettingsPrivacyRoute: typeof AuthenticatedAppSettingsPrivacyRoute
  AuthenticatedAppSettingsReportRoute: typeof AuthenticatedAppSettingsReportRoute
  AuthenticatedAppSettingsTermsRoute: typeof AuthenticatedAppSettingsTermsRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppMessagesIndexRoute: typeof AuthenticatedAppMessagesIndexRoute
  AuthenticatedAppPrideIndexRoute: typeof AuthenticatedAppPrideIndexRoute
  AuthenticatedAppProfileIndexRoute: typeof AuthenticatedAppProfileIndexRoute
  AuthenticatedAppRewardsIndexRoute: typeof AuthenticatedAppRewardsIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppEventsEventIdEditRoute: typeof AuthenticatedAppEventsEventIdEditRoute
  AuthenticatedAppEventsEventIdIndexRoute: typeof AuthenticatedAppEventsEventIdIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRoute,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppIcebreakerRoute: AuthenticatedAppIcebreakerRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPremiumRoute: AuthenticatedAppPremiumRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppChatGroupIdRoute: AuthenticatedAppChatGroupIdRoute,
  AuthenticatedAppMessagesThreadIdRoute: AuthenticatedAppMessagesThreadIdRoute,
  AuthenticatedAppPostsPostIdRoute: AuthenticatedAppPostsPostIdRoute,
  AuthenticatedAppPrideGuidelinesRoute: AuthenticatedAppPrideGuidelinesRoute,
  AuthenticatedAppPrideNotificationsRoute:
    AuthenticatedAppPrideNotificationsRoute,
  AuthenticatedAppPrideSetupRoute: AuthenticatedAppPrideSetupRoute,
  AuthenticatedAppProfileEditRoute: AuthenticatedAppProfileEditRoute,
  AuthenticatedAppSettingsBlockedRoute: AuthenticatedAppSettingsBlockedRoute,
  AuthenticatedAppSettingsHelpRoute: AuthenticatedAppSettingsHelpRoute,
  AuthenticatedAppSettingsPasswordRoute: AuthenticatedAppSettingsPasswordRoute,
  AuthenticatedAppSettingsPhoneRoute: AuthenticatedAppSettingsPhoneRoute,
  AuthenticatedAppSettingsPrivacyRoute: AuthenticatedAppSettingsPrivacyRoute,
  AuthenticatedAppSettingsReportRoute: AuthenticatedAppSettingsReportRoute,
  AuthenticatedAppSettingsTermsRoute: AuthenticatedAppSettingsTermsRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
  AuthenticatedAppMessagesIndexRoute: AuthenticatedAppMessagesIndexRoute,
  AuthenticatedAppPrideIndexRoute: AuthenticatedAppPrideIndexRoute,
  AuthenticatedAppProfileIndexRoute: AuthenticatedAppProfileIndexRoute,
  AuthenticatedAppRewardsIndexRoute: AuthenticatedAppRewardsIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppEventsEventIdEditRoute:
    AuthenticatedAppEventsEventIdEditRoute,
  AuthenticatedAppEventsEventIdIndexRoute:
    AuthenticatedAppEventsEventIdIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminEngagementRoute: typeof AdminEngagementRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFlaggedRoute: typeof AdminFlaggedRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEngagementRoute: AdminEngagementRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFlaggedRoute: AdminFlaggedRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
