/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/_app/requests'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app/notifications'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/_app/messages'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/_app/home'
import { Route as AuthenticatedAppEventsRouteImport } from './routes/_authenticated/_app/events'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/_app/create'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app/chat'
import { Route as AuthenticatedAppProfileIndexRouteImport } from './routes/_authenticated/_app/profile.index'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated/_app/u.$userId'
import { Route as AuthenticatedAppProfileEditRouteImport } from './routes/_authenticated/_app/profile.edit'
import { Route as AuthenticatedAppMessagesThreadIdRouteImport } from './routes/_authenticated/_app/messages.$threadId'
import { Route as AuthenticatedAppEventsEventIdRouteImport } from './routes/_authenticated/_app/events.$eventId'
import { Route as AuthenticatedAppChatGroupIdRouteImport } from './routes/_authenticated/_app/chat.$groupId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEventsRoute = AuthenticatedAppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileIndexRoute =
  AuthenticatedAppProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileEditRoute =
  AuthenticatedAppProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesThreadIdRoute =
  AuthenticatedAppMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAppMessagesRoute,
  } as any)
const AuthenticatedAppEventsEventIdRoute =
  AuthenticatedAppEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedAppEventsRoute,
  } as any)
const AuthenticatedAppChatGroupIdRoute =
  AuthenticatedAppChatGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/create': typeof AuthenticatedAppCreateRoute
  '/events': typeof AuthenticatedAppEventsRouteWithChildren
  '/home': typeof AuthenticatedAppHomeRoute
  '/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/profile/': typeof AuthenticatedAppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/create': typeof AuthenticatedAppCreateRoute
  '/events': typeof AuthenticatedAppEventsRouteWithChildren
  '/home': typeof AuthenticatedAppHomeRoute
  '/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/profile': typeof AuthenticatedAppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/_app/create': typeof AuthenticatedAppCreateRoute
  '/_authenticated/_app/events': typeof AuthenticatedAppEventsRouteWithChildren
  '/_authenticated/_app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/_app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/_app/chat/$groupId': typeof AuthenticatedAppChatGroupIdRoute
  '/_authenticated/_app/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/_authenticated/_app/messages/$threadId': typeof AuthenticatedAppMessagesThreadIdRoute
  '/_authenticated/_app/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/_authenticated/_app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/_authenticated/_app/profile/': typeof AuthenticatedAppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pending'
    | '/chat'
    | '/create'
    | '/events'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/requests'
    | '/chat/$groupId'
    | '/events/$eventId'
    | '/messages/$threadId'
    | '/profile/edit'
    | '/u/$userId'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pending'
    | '/chat'
    | '/create'
    | '/events'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/requests'
    | '/chat/$groupId'
    | '/events/$eventId'
    | '/messages/$threadId'
    | '/profile/edit'
    | '/u/$userId'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/create'
    | '/_authenticated/_app/events'
    | '/_authenticated/_app/home'
    | '/_authenticated/_app/messages'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/requests'
    | '/_authenticated/_app/chat/$groupId'
    | '/_authenticated/_app/events/$eventId'
    | '/_authenticated/_app/messages/$threadId'
    | '/_authenticated/_app/profile/edit'
    | '/_authenticated/_app/u/$userId'
    | '/_authenticated/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/requests': {
      id: '/_authenticated/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages': {
      id: '/_authenticated/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/home': {
      id: '/_authenticated/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/events': {
      id: '/_authenticated/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedAppEventsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/create': {
      id: '/_authenticated/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/': {
      id: '/_authenticated/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedAppProfileIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/u/$userId': {
      id: '/_authenticated/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/edit': {
      id: '/_authenticated/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedAppProfileEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/$threadId': {
      id: '/_authenticated/_app/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedAppMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppMessagesRoute
    }
    '/_authenticated/_app/events/$eventId': {
      id: '/_authenticated/_app/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedAppEventsRoute
    }
    '/_authenticated/_app/chat/$groupId': {
      id: '/_authenticated/_app/chat/$groupId'
      path: '/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedAppChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatGroupIdRoute: typeof AuthenticatedAppChatGroupIdRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatGroupIdRoute: AuthenticatedAppChatGroupIdRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppEventsRouteChildren {
  AuthenticatedAppEventsEventIdRoute: typeof AuthenticatedAppEventsEventIdRoute
}

const AuthenticatedAppEventsRouteChildren: AuthenticatedAppEventsRouteChildren =
  {
    AuthenticatedAppEventsEventIdRoute: AuthenticatedAppEventsEventIdRoute,
  }

const AuthenticatedAppEventsRouteWithChildren =
  AuthenticatedAppEventsRoute._addFileChildren(
    AuthenticatedAppEventsRouteChildren,
  )

interface AuthenticatedAppMessagesRouteChildren {
  AuthenticatedAppMessagesThreadIdRoute: typeof AuthenticatedAppMessagesThreadIdRoute
}

const AuthenticatedAppMessagesRouteChildren: AuthenticatedAppMessagesRouteChildren =
  {
    AuthenticatedAppMessagesThreadIdRoute:
      AuthenticatedAppMessagesThreadIdRoute,
  }

const AuthenticatedAppMessagesRouteWithChildren =
  AuthenticatedAppMessagesRoute._addFileChildren(
    AuthenticatedAppMessagesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRoute
  AuthenticatedAppEventsRoute: typeof AuthenticatedAppEventsRouteWithChildren
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppProfileEditRoute: typeof AuthenticatedAppProfileEditRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
  AuthenticatedAppProfileIndexRoute: typeof AuthenticatedAppProfileIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRoute,
  AuthenticatedAppEventsRoute: AuthenticatedAppEventsRouteWithChildren,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppProfileEditRoute: AuthenticatedAppProfileEditRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
  AuthenticatedAppProfileIndexRoute: AuthenticatedAppProfileIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
